data:
  raw_path: "data/raw/Heart Attack.csv"
  processed_path: "data/preprocessed/heart_attack_processed.csv"
  train_path: "data/preprocessed/heart_attack_processed_train.csv"     # Fixed
  test_path: "data/preprocessed/heart_attack_processed_test.csv"       # Fixed
  
preprocessing:
  test_size: 0.2
  random_state: 42
  features: ["age", "gender", "pressurehight", "pressurelow", "glucose", "kcm", "troponin"]
  target: "class"
  drop_columns: ["impluse"]

model:
  algorithm: "random_forest"
  random_state: 42
  n_estimators: 100
  max_depth: null
  min_samples_split: 2
  min_samples_leaf: 1
  
evaluation:
  metrics: ["accuracy", "precision", "recall", "f1_score", "roc_auc"]
  cv_folds: 5

api:
  host: "0.0.0.0"
  port: 5000
  debug: false
